spring.application.name=telemedicine-clinic-system

spring.datasource.url=jdbc:mysql://localhost:3306/telemedclinic 
spring.datasource.username=telemeduser
spring.datasource.password=Telemed123!

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

server.address=0.0.0.0
server.port=8080